### ISSUE TITLE
I Made API tool out of highlight.js

### ISSUE THREAD

**Issue by jimmywarting** [soulshined/ft-syntax-highlight#1]
I was like you - but the idea of having to manually having to write the code with classes are tedious. So i made a tool out of highlight.js that would remove the dependency of css and js and just only put the finished formated code into the place where i want it

https://highlight-saas.herokuapp.com

**Comment by soulshined** [comment]
I don't see this as an issue directly related to this repo, mostly a way to self advertise @jimmywarting Although, I agree with you, it can be tedious, but this project is pure-CSS for a reason and there are plenty of pure-CSSers out there in the wild. Thank you for your feedback however. Closing as off-topic.
